# Generated by Django 5.1 on 2024-08-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0002_confession'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='title',
            field=models.CharField(default='anonymous confession', max_length=100),
        ),
    ]
