# Generated by Django 5.1 on 2024-08-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0003_confession_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='confession',
            new_name='confession_model',
        ),
    ]
